// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokMultilink, StoryblokRichTextDoc, StoryblokAsset } from './storyblok/storyblok';
export interface Article {
  image?: StoryblokAsset;
  title?: string;
  teaser?: string;
  content?: StoryblokRichTextDoc;
  component: "article";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Config {
  header_menu?: MenuLink[];
  component: "config";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (Article | Config | Grid | Hero | MenuLink | Page | PopularArticles | Teaser | Text)[];
  component: "grid";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Hero {
  headline?: string;
  subheadline?: string;
  background_image?: StoryblokAsset;
  layout?: "" | "constrained" | "full-width";
  component: "hero";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface MenuLink {
  label?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "menu_link";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Page {
  body?: (Grid | Hero | PopularArticles | Text)[];
  component: "page";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface PopularArticles {
  headline?: string;
  articles?: (ISbStoryData<Article> | string)[];
  component: "popular-articles";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Teaser {
  image?: StoryblokAsset;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  description?: string;
  headline?: string;
  component: "teaser";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export interface Text {
  headline?: string;
  text?: StoryblokRichTextDoc;
  component: "text";
  _uid: string;
  _editable?: string | undefined;
  [k: string]: unknown;
}

export type ContentType = Article | Config | Page;
